// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlPFn_Zlnh9WqAfseEPSQ_GKLaquoSg0A',
    appId: '1:916440552847:web:b7118275d601a9c828e7fa',
    messagingSenderId: '916440552847',
    projectId: 'cmd-final',
    authDomain: 'cmd-final.firebaseapp.com',
    storageBucket: 'cmd-final.firebasestorage.app',
    measurementId: 'G-7VSNWBW58M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97UNYydKK4szsQY_4e2D_CarA8Hw-bkc',
    appId: '1:916440552847:android:3013eb3497b04bc528e7fa',
    messagingSenderId: '916440552847',
    projectId: 'cmd-final',
    storageBucket: 'cmd-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxAn25aSxAUnlQTRxlayCpaafIWXRU7s',
    appId: '1:916440552847:ios:93f20e3b90dc844428e7fa',
    messagingSenderId: '916440552847',
    projectId: 'cmd-final',
    storageBucket: 'cmd-final.firebasestorage.app',
    iosBundleId: 'com.example.cmdFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxAn25aSxAUnlQTRxlayCpaafIWXRU7s',
    appId: '1:916440552847:ios:93f20e3b90dc844428e7fa',
    messagingSenderId: '916440552847',
    projectId: 'cmd-final',
    storageBucket: 'cmd-final.firebasestorage.app',
    iosBundleId: 'com.example.cmdFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlPFn_Zlnh9WqAfseEPSQ_GKLaquoSg0A',
    appId: '1:916440552847:web:951a29791f0ef57728e7fa',
    messagingSenderId: '916440552847',
    projectId: 'cmd-final',
    authDomain: 'cmd-final.firebaseapp.com',
    storageBucket: 'cmd-final.firebasestorage.app',
    measurementId: 'G-3YNV8HG203',
  );
}
